---
kind: StoragePoolClaim
apiVersion: openebs.io/v1alpha1
metadata:
  name: cstor
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
          memory: 2Gi
      - name: PoolResourceLimits
        value: |-
          memory: 4Gi
spec:
  name: cstor
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList
    - blockdevice-06410c91410493c86969c212d9735342
    - blockdevice-e927d12d98e7fa32fd5870e1397b7e37
